blank_issues_enabled: true
contact_links:
  - name: 💬 Telegram Community Group
    url: https://t.me/+CsxZGItXdW40ZWVl
    about: Join our community on Telegram for discussions and real-time support.
  - name: 📖 Usage Documentation & Tutorial
    url: https://docs.google.com/document/d/1fFEz3k7ATdN2dwY1L3RJn1QuzgokIsslNa88-vUPxPk/edit?usp=sharing
    about: Read the comprehensive LocationSpoofer user guide and tutorials.
